In [175]:
import pandas as pd

In [176]:
import matplotlib.pyplot as plt

In [177]:
import seaborn as sns

In [178]:
df = pd.read_csv("sample_data/cc1.csv")

In [179]:
df = df.fillna(-100)

In [180]:
dfL = pd.read_csv("sample_data/label.csv")

In [181]:
import numpy as np

In [182]:
df

6  160    438    479    618    958  1195  1228   1516   1551  ...  \
0       1.0   31    1.0    1.0    1.0    1.0    52  0.89    1.0    1.0  ...   
1    -100.0   19 -100.0 -100.0    1.0    1.0    55  0.73 -100.0 -100.0  ...   
2    -100.0   40 -100.0 -100.0 -100.0 -100.0    69  0.38 -100.0 -100.0  ...   
3    -100.0   30 -100.0 -100.0 -100.0 -100.0    86  0.84 -100.0 -100.0  ...   
4    -100.0   95 -100.0 -100.0 -100.0    1.0     5  0.43 -100.0 -100.0  ...   
...     ...  ...    ...    ...    ...    ...   ...   ...    ...    ...  ...   
1837 -100.0   52 -100.0 -100.0 -100.0 -100.0    45  0.48 -100.0 -100.0  ...   
1838 -100.0    6 -100.0 -100.0 -100.0 -100.0    63  0.95 -100.0 -100.0  ...   
1839 -100.0   77 -100.0    1.0 -100.0 -100.0    63  0.71 -100.0 -100.0  ...   
1840 -100.0   89 -100.0 -100.0 -100.0 -100.0    97  0.43 -100.0 -100.0  ...   
1841 -100.0   21 -100.0 -100.0 -100.0 -100.0    98  0.02 -100.0 -100.0  ...   

      25562   9194  21372  22326  23012   6133   8860  12035  21037  23840  
0    -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  
1    -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  
2    -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  
3    -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  
4    -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
1837 -100.0    1.0    1.0    1.0    1.0 -100.0 -100.0 -100.0 -100.0 -100.0  
1838 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  
1839 -100.0 -100.0 -100.0 -100.0 -100.0    1.0 -100.0 -100.0 -100.0 -100.0  
1840 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0  
1841 -100.0 -100.0 -100.0 -100.0 -100.0 -100.0    1.0    1.0    2.0    1.0  

[1842 rows x 13456 columns]

In [183]:
dfL

label
0         1
1         1
2         1
3         1
4         1
...     ...
1837     -1
1838     -1
1839      1
1840     -1
1841      1

[1842 rows x 1 columns]

In [184]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [185]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import warnings
warnings.filterwarnings('ignore')

# Naive_Bayes Classifier  
def naive_bayes_classifier(train_x, train_y):
    from sklearn.naive_bayes import MultinomialNB
    model = MultinomialNB(alpha=0.01)
    model.fit(train_x, train_y)
    return model
    
# Decision Tree Classifier  
def decision_tree_classifier(train_x, train_y):  
    from sklearn import tree  
    model = tree.DecisionTreeClassifier()  
    model.fit(train_x, train_y)  
    return model  
  
# KNN Classifier  
def knn_classifier(train_x, train_y):  
    from sklearn.neighbors import KNeighborsClassifier  
    model = KNeighborsClassifier()  
    model.fit(train_x, train_y)  
    return model  
  
  
# Logistic Regression Classifier  
def logistic_regression_classifier(train_x, train_y):  
    from sklearn.linear_model import LogisticRegression  
    model = LogisticRegression(penalty='l2')  
    model.fit(train_x, train_y)  
    return model  

def gradient_boosting_classifier(train_x, train_y):  
    from sklearn.ensemble import GradientBoostingClassifier  
    model = GradientBoostingClassifier()
    # model = GradientBoostingClassifier(learning_rate=0.01, n_estimators=1500,max_depth=7, min_samples_split=2, min_samples_leaf=1, subsample=1,max_features='sqrt', random_state=10) 
    model.fit(train_x, train_y)  
    return model  
  
# SVM Classifier  
def svm_classifier(train_x, train_y):  
    from sklearn.svm import SVC  
    model = SVC(kernel='rbf', probability=True)  
    model.fit(train_x, train_y)  
    return model  
  
# Random Forest Classifier  
def random_forest_classifier(train_x, train_y):  
    from sklearn.ensemble import RandomForestClassifier  
    model = RandomForestClassifier(n_estimators=100)  
    model.fit(train_x, train_y)  
    return model  

In [186]:
x = df
y = dfL
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 42)
   

In [187]:
x_train,x_test,y_train,y_test

(          6  160    438    479    618    958  1195  1228   1516   1551  ...  \
 588  -100.0   46 -100.0 -100.0 -100.0 -100.0    27  0.08 -100.0 -100.0  ...   
 949  -100.0   76 -100.0 -100.0 -100.0 -100.0     5  0.08 -100.0 -100.0  ...   
 1632 -100.0   55 -100.0    1.0 -100.0    1.0     2  0.19 -100.0 -100.0  ...   
 1368 -100.0   95 -100.0 -100.0 -100.0 -100.0    27  0.60 -100.0 -100.0  ...   
 1339 -100.0   46 -100.0 -100.0 -100.0    2.0    81  0.74 -100.0    1.0  ...   
 ...     ...  ...    ...    ...    ...    ...   ...   ...    ...    ...  ...   
 1130    1.0   70 -100.0 -100.0 -100.0 -100.0    80  0.88 -100.0 -100.0  ...   
 1294 -100.0   56 -100.0 -100.0    1.0 -100.0    46  0.76 -100.0 -100.0  ...   
 860  -100.0   73 -100.0 -100.0 -100.0 -100.0    14  0.03 -100.0 -100.0  ...   
 1459 -100.0   11 -100.0 -100.0 -100.0 -100.0    18  0.62 -100.0 -100.0  ...   
 1126 -100.0   20 -100.0 -100.0 -100.0 -100.0    57  0.23 -100.0 -100.0  ...   
 
       25562   9194  21372  22326  230

In [188]:
test_classifiers = [
    #'MB', 
    #'KNN', 
    'LR', 
    'RF',
    #'DT',
    #'SVM',
    #'GBDT'
    ]


classifiers = {
    
             #'MB':naive_bayes_classifier,
              #'KNN':knn_classifier,
               'LR':logistic_regression_classifier,
               'RF':random_forest_classifier,
               #'DT':decision_tree_classifier,
               #'SVM':svm_classifier,
               #'GBDT':gradient_boosting_classifier
}

In [189]:
for classifier in test_classifiers: 
    print('******************* %s ********************' % classifier) 
  
    model = classifiers[classifier](x_train, y_train) 
  
    predict = model.predict(x_test) 
    train_out = model.predict(x_train) 
  
    matrix = confusion_matrix(y_test, predict) 
    print(matrix) 
    class_report = classification_report(y_test, predict) 
    print(class_report)

******************* LR ********************
[[126   4]
 [  2 237]]
              precision    recall  f1-score   support

          -1       0.98      0.97      0.98       130
           1       0.98      0.99      0.99       239

    accuracy                           0.98       369
   macro avg       0.98      0.98      0.98       369
weighted avg       0.98      0.98      0.98       369

******************* RF ********************
[[122   8]
 [  1 238]]
              precision    recall  f1-score   support

          -1       0.99      0.94      0.96       130
           1       0.97      1.00      0.98       239

    accuracy                           0.98       369
   macro avg       0.98      0.97      0.97       369
weighted avg       0.98      0.98      0.98       369



In [190]:
df2 = pd.read_csv("sample_data/cc2.csv")

In [191]:
df2 = df2.fillna(-100)

In [192]:
x = df2

In [193]:
test_classifiers = [
    #'MB', 
    #'KNN', 
    'LR', 
    #'RF',
    #'DT',
    #'SVM',
    #'GBDT'
    ]


classifiers = {
    
             #'MB':naive_bayes_classifier,
              #'KNN':knn_classifier,
               'LR':logistic_regression_classifier,
               #'RF':random_forest_classifier,
               #'DT':decision_tree_classifier,
               #'SVM':svm_classifier,
               #'GBDT':gradient_boosting_classifier
}

In [194]:
for classifier in test_classifiers: 
    print('******************* %s ********************' % classifier) 
  
 
    predict = model.predict(x_test) 
    
  
    matrix = confusion_matrix(y_test, predict) 
    print(matrix) 
    class_report = classification_report(y_test, predict) 
    print(class_report)

******************* LR ********************
[[122   8]
 [  1 238]]
              precision    recall  f1-score   support

          -1       0.99      0.94      0.96       130
           1       0.97      1.00      0.98       239

    accuracy                           0.98       369
   macro avg       0.98      0.97      0.97       369
weighted avg       0.98      0.98      0.98       369

