In [10]:
import pandas as pd

In [11]:
import matplotlib.pyplot as plt

In [12]:
import seaborn as sns

In [13]:
df = pd.read_csv("sample_data/loan_sanction.csv")

In [14]:
import numpy as np

In [18]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [19]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [20]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import warnings
warnings.filterwarnings('ignore')

# Naive_Bayes Classifier  
def naive_bayes_classifier(train_x, train_y):
    from sklearn.naive_bayes import MultinomialNB
    model = MultinomialNB(alpha=0.01)
    model.fit(train_x, train_y)
    return model
    
# Decision Tree Classifier  
def decision_tree_classifier(train_x, train_y):  
    from sklearn import tree  
    model = tree.DecisionTreeClassifier()  
    model.fit(train_x, train_y)  
    return model  
  
# KNN Classifier  
def knn_classifier(train_x, train_y):  
    from sklearn.neighbors import KNeighborsClassifier  
    model = KNeighborsClassifier()  
    model.fit(train_x, train_y)  
    return model  
  
  
# Logistic Regression Classifier  
def logistic_regression_classifier(train_x, train_y):  
    from sklearn.linear_model import LogisticRegression  
    model = LogisticRegression(penalty='l2')  
    model.fit(train_x, train_y)  
    return model  

def gradient_boosting_classifier(train_x, train_y):  
    from sklearn.ensemble import GradientBoostingClassifier  
    model = GradientBoostingClassifier()
    # model = GradientBoostingClassifier(learning_rate=0.01, n_estimators=1500,max_depth=7, min_samples_split=2, min_samples_leaf=1, subsample=1,max_features='sqrt', random_state=10) 
    model.fit(train_x, train_y)  
    return model  
  
# SVM Classifier  
def svm_classifier(train_x, train_y):  
    from sklearn.svm import SVC  
    model = SVC(kernel='rbf', probability=True)  
    model.fit(train_x, train_y)  
    return model  
  
# Random Forest Classifier  
def random_forest_classifier(train_x, train_y):  
    from sklearn.ensemble import RandomForestClassifier  
    model = RandomForestClassifier(n_estimators=100)  
    model.fit(train_x, train_y)  
    return model  

In [30]:
def get_data():
    df = pd.read_csv("sample_data/loan_sanction.csv")
    print(df.info())
  


    
    print(df.shape)
    from sklearn.preprocessing import LabelEncoder
    df = df.apply(LabelEncoder().fit_transform) # Transforming data with string in the entire dataframe to int
    df = df.drop(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education'], axis = 1).fillna(-100)   
    
        
    
    print(df.describe().T)
   

    #spliting data for input and output
    x=df.iloc[:,:-1]
    y=df.iloc[:,-1]
    

    # from sklearn.model_selection import train_test_split
    # x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)
    if(x.shape[0]==y.shape[0]):
        a = round (x.shape[0]*0.8)
        x_train = x.iloc[0:a] 
        x_test = x.iloc[a:] 
        y_train = y[0:a] 
        y_test = y[a:] 
        
        print(x_train.shape)
        print(x_test.shape)
        print(y_train.shape)
        print(y_test.shape) 
        print(x_train.info()) 
        print(y_train.info())   
    else:
        print("The length of x and y are not the same!")
    
  
    # from sklearn.preprocessing import MinMaxScaler
    # scaler = MinMaxScaler()
    # scaler.fit(x_train)
    # x_train = scaler.fit_transform(x_train)
    # x_test = scaler.fit_transform(x_test)
    return x_train,x_test,y_train,y_test

In [31]:
x_train,x_test,y_train,y_test = get_data()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB
None
(614, 13)
                   count        mean         std  min     25%    50%     75%  \
Self_Employed    

In [32]:
test_classifiers = [
    #'MB', 
    #'KNN', 
    'LR', 
    #'RF',
    #'DT',
    #'SVM',
    'GBDT'
    ]


classifiers = {
    
             #'MB':naive_bayes_classifier,
              #'KNN':knn_classifier,
               'LR':logistic_regression_classifier,
               #'RF':random_forest_classifier,
               #'DT':decision_tree_classifier,
               #'SVM':svm_classifier,
               'GBDT':gradient_boosting_classifier
}

In [33]:
for classifier in test_classifiers: 
    print('******************* %s ********************' % classifier) 
  
    model = classifiers[classifier](x_train, y_train) 
  
    predict = model.predict(x_test) 
    train_out = model.predict(x_train) 
  
    matrix = confusion_matrix(y_test, predict) 
    print(matrix) 
    class_report = classification_report(y_test, predict) 
    print(class_report)

******************* LR ********************
[[18 21]
 [ 1 83]]
              precision    recall  f1-score   support

           0       0.95      0.46      0.62        39
           1       0.80      0.99      0.88        84

    accuracy                           0.82       123
   macro avg       0.87      0.72      0.75       123
weighted avg       0.85      0.82      0.80       123

******************* GBDT ********************
[[20 19]
 [ 5 79]]
              precision    recall  f1-score   support

           0       0.80      0.51      0.62        39
           1       0.81      0.94      0.87        84

    accuracy                           0.80       123
   macro avg       0.80      0.73      0.75       123
weighted avg       0.80      0.80      0.79       123



In [26]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)
matrix=confusion_matrix(y_test, y_pred)
print(matrix)
class_report=classification_report(y_test, y_pred)
print(class_report)

[[18 21]
 [ 1 83]]
              precision    recall  f1-score   support

           0       0.95      0.46      0.62        39
           1       0.80      0.99      0.88        84

    accuracy                           0.82       123
   macro avg       0.87      0.72      0.75       123
weighted avg       0.85      0.82      0.80       123



In [34]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)
matrix=confusion_matrix(y_test, y_pred)
print(matrix)
class_report=classification_report(y_test, y_pred)
print(class_report)

[[20 19]
 [ 5 79]]
              precision    recall  f1-score   support

           0       0.80      0.51      0.62        39
           1       0.81      0.94      0.87        84

    accuracy                           0.80       123
   macro avg       0.80      0.73      0.75       123
weighted avg       0.80      0.80      0.79       123

